### ISSUE TITLE
执行脚本后只输出版本号是否成功？

### ISSUE THREAD

**Issue by lovelyded** [ttlxihuan/shell#1]
执行脚本后只输出版本号，但是看脚本的结尾是会输出安装成功+版本号的吧？只输出版本号是什么情况呢

**Comment by ttlxihuan** [comment]
直接运行脚本不指定版本参数是只输出最新可安装版本号，如果需要安装必需指定版本号，比如：

安装最新稳定版本：
bash nginx-install.sh new

安装指定版本：
bash nginx-install.sh 1.20.1

目前脚本安装兼容性问题还不是很到位，有安装失败时建议排查下相关依赖是否到位。
